### ISSUE TITLE
Test en erreur intermittente

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#1439]
https://circleci.com/gh/betagouv/tps/5935#tests/containers/2

```
#!/bin/bash -eo pipefail
bundle exec rspec --profile 10 \
  --format RspecJunitFormatter \
  --out ~/test_results/rspec.xml \
  --format progress \
  $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
Run options:
  include {:focus=>true}
  exclude {:disable=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 37769
...................................................................F.......................................................................................................................F....F....................................................................................................................................................................................................................................................................................................................................................................................................

Failures:

  1) As a User I want to sort and paginate dossiers After sign_in, I can see my 51 dossiers on the index Using pagination
     Failure/Error: page.evaluate_script('jQuery.active').zero?
     
     Timeout::Error:
       execution expired
     # ./spec/support/wait_for_ajax.rb:10:in `finished_all_ajax_requests?'
     # ./spec/support/wait_for_ajax.rb:5:in `block in wait_for_ajax'
     # ./spec/support/wait_for_ajax.rb:4:in `wait_for_ajax'
     # ./spec/features/users/dossier_index_spec.rb:39:in `block (3 levels) in <top (required)>'

  2) Admin::ProceduresController GET #path_list when no params should eq "fake_path127"
     Failure/Error: it { expect(body.second['label']).to eq(procedure2.path) }
     
       expected: "fake_path127"
            got: "fake_path128"
     
       (compared using ==)
     # ./spec/controllers/admin/procedures_controller_spec.rb:509:in `block (4 levels) in <top (required)>'

  3) Admin::ProceduresController GET #path_list when no params should eq "fake_path141"
     Failure/Error: it { expect(body.first['label']).to eq(procedure.path) }
     
       expected: "fake_path141"
            got: "fake_path143"
     
       (compared using ==)
     # ./spec/controllers/admin/procedures_controller_spec.rb:507:in `block (4 levels) in <top (required)>'

Top 10 slowest examples (65.73 seconds, 54.7% of total time):
  on click on tabs button when user is logged in when he click on tabs en examen it redirect to users dossier termine
    39.32 seconds ./spec/features/users/onglets_link_spec.rb:38
  As a User I want to sort and paginate dossiers After sign_in, I can see my 51 dossiers on the index Using pagination
    7.49 seconds ./spec/features/users/dossier_index_spec.rb:35
  As a User I want to sort and paginate dossiers After sign_in, I can see my 51 dossiers on the index Using sort
    5.31 seconds ./spec/features/users/dossier_index_spec.rb:23
  procedure filters should add be able to add and remove custom type_de_champ column
    3.43 seconds ./spec/features/new_gestionnaire/procedure_filters_spec.rb:42
  procedure filters should be able to add and remove filter
    2.58 seconds ./spec/features/new_gestionnaire/procedure_filters_spec.rb:56
  add a new type de piece justificative when there is no piece justificative when user fills field and submit when user change existing type de pj saves change in database
    1.6 seconds ./spec/features/admin/add_type_de_piece_justificative_spec.rb:67
  procedure filters should add be able to add created_at column
    1.58 seconds ./spec/features/new_gestionnaire/procedure_filters_spec.rb:34
  new_gestionnaire/dossiers/show.html.haml when dossier was created by an entreprise should include "44011762001530"
    1.56 seconds ./spec/views/new_gestionnaire/dossiers/show.html.haml_spec.rb:19
  add a new type de piece justificative when there is no piece justificative when user fills field and submit when user delete pj removes pj from page
    1.54 seconds ./spec/features/admin/add_type_de_piece_justificative_spec.rb:52
  add a new type de piece justificative when there is no piece justificative when user fills field and submit displays new created pj
    1.31 seconds ./spec/features/admin/add_type_de_piece_justificative_spec.rb:36

Top 10 slowest example groups:
  on click on tabs button
    10.3 seconds average (41.21 seconds / 4 examples) ./spec/features/users/onglets_link_spec.rb:3
  As a User I want to sort and paginate dossiers
    6.4 seconds average (12.8 seconds / 2 examples) ./spec/features/users/dossier_index_spec.rb:3
  procedure filters
    1.66 seconds average (8.29 seconds / 5 examples) ./spec/features/new_gestionnaire/procedure_filters_spec.rb:3
  add a new type de piece justificative
    1.21 seconds average (6.05 seconds / 5 examples) ./spec/features/admin/add_type_de_piece_justificative_spec.rb:3
  move up button type de champs
    1.13 seconds average (1.13 seconds / 1 example) ./spec/features/admin/move_up_type_de_champ_private_spec.rb:3
  StatsController
    0.45488 seconds average (6.82 seconds / 15 examples) ./spec/controllers/stats_controller_spec.rb:3
  new_gestionnaire/dossiers/show.html.haml
    0.27652 seconds average (2.77 seconds / 10 examples) ./spec/views/new_gestionnaire/dossiers/show.html.haml_spec.rb:1
  AutoArchiveProcedureJob
    0.23485 seconds average (3.05 seconds / 13 examples) ./spec/jobs/auto_archive_procedure_job_spec.rb:3
  users/recapitulatif/show.html.haml
    0.20776 seconds average (3.53 seconds / 17 examples) ./spec/views/users/recapitulatif/show.html.haml_spec.rb:3
  procedure locked
    0.19671 seconds average (0.19671 seconds / 1 example) ./spec/features/admin/procedure_locked_spec.rb:3

Finished in 2 minutes 0.2 seconds (files took 18.48 seconds to load)
581 examples, 3 failures

Failed examples:

rspec ./spec/features/users/dossier_index_spec.rb:35 # As a User I want to sort and paginate dossiers After sign_in, I can see my 51 dossiers on the index Using pagination
rspec ./spec/controllers/admin/procedures_controller_spec.rb:509 # Admin::ProceduresController GET #path_list when no params should eq "fake_path127"
rspec ./spec/controllers/admin/procedures_controller_spec.rb:507 # Admin::ProceduresController GET #path_list when no params should eq "fake_path141"

Randomized with seed 37769

Exited with code 1
```

**Comment by fredZen** [comment]
Le `page.evaluate_script('jQuery.active').zero?` semble revenir en force ces derniers temps !

**Comment by kemenaran** [comment]
Pas vu ce test foirer récemment. Je ferme.
