### ISSUE TITLE
Test spec/models/gestionnaire_spec.rb pas fiable

### ISSUE THREAD

**Issue by fredZen** [betagouv/tps#2140]
https://circleci.com/gh/betagouv/tps/11926#tests/containers/1

```
#!/bin/bash -eo pipefail
bundle exec rspec --profile 10 \
  --format RspecJunitFormatter \
  --out ~/test_results/rspec.xml \
  --format progress \
  $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
Requested historical based timing, but they are not present.  Falling back to name based sorting
Run options:
  include {:focus=>true}
  exclude {:disable=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 34033
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.FFFF...FFF...FFF..FFF.........................................................................................................................................................................................................................................................................................................................................*......

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ApplicationJob perform 
     # No reason given
     # ./spec/jobs/application_job_spec.rb:6


Failures:

  1) Gestionnaire#notifications_for_dossier messagerie when there is a new commentaire should match {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>true}
     Failure/Error: it { is_expected.to match({ demande: false, annotations_privees: false, avis: false, messagerie: true }) }
     
       expected {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>false} to match {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>true}
       Diff:
       @@ -1,5 +1,5 @@
        :annotations_privees => false,
        :avis => false,
        :demande => false,
       -:messagerie => true,
       +:messagerie => false,
       
     # ./spec/models/gestionnaire_spec.rb:245:in `block (5 levels) in <top (required)>'

  2) Gestionnaire#notifications_for_dossier when there is a modification on a piece jusitificative should match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
     Failure/Error: it { is_expected.to match({ demande: true, annotations_privees: false, avis: false, messagerie: false }) }
     
       expected {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>false} to match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
       Diff:
       @@ -1,5 +1,5 @@
        :annotations_privees => false,
        :avis => false,
       -:demande => true,
       +:demande => false,
        :messagerie => false,
       
     # ./spec/models/gestionnaire_spec.rb:226:in `block (4 levels) in <top (required)>'

  3) Gestionnaire#notifications_for_dossier when there is a modification on private champs should match {:demande=>false, :annotations_privees=>true, :avis=>false, :messagerie=>false}
     Failure/Error: it { is_expected.to match({ demande: false, annotations_privees: true, avis: false, messagerie: false }) }
     
       expected {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>false} to match {:demande=>false, :annotations_privees=>true, :avis=>false, :messagerie=>false}
       Diff:
       @@ -1,4 +1,4 @@
       -:annotations_privees => true,
       +:annotations_privees => false,
        :avis => false,
        :demande => false,
        :messagerie => false,
       
     # ./spec/models/gestionnaire_spec.rb:232:in `block (4 levels) in <top (required)>'

  4) Gestionnaire#notifications_for_dossier when there is a modification on avis should match {:demande=>false, :annotations_privees=>false, :avis=>true, :messagerie=>false}
     Failure/Error: it { is_expected.to match({ demande: false, annotations_privees: false, avis: true, messagerie: false }) }
     
       expected {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>false} to match {:demande=>false, :annotations_privees=>false, :avis=>true, :messagerie=>false}
       Diff:
       @@ -1,5 +1,5 @@
        :annotations_privees => false,
       -:avis => true,
       +:avis => false,
        :demande => false,
        :messagerie => false,
       
     # ./spec/models/gestionnaire_spec.rb:238:in `block (4 levels) in <top (required)>'

  5) Gestionnaire#notifications_for_dossier when there is a modification on public champs should match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
     Failure/Error: it { is_expected.to match({ demande: true, annotations_privees: false, avis: false, messagerie: false }) }
     
       expected {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>false} to match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
       Diff:
       @@ -1,5 +1,5 @@
        :annotations_privees => false,
        :avis => false,
       -:demande => true,
       +:demande => false,
        :messagerie => false,
       
     # ./spec/models/gestionnaire_spec.rb:220:in `block (4 levels) in <top (required)>'

  6) Gestionnaire#notifications_per_procedure when there is a modification on public champs should match {75=>1}
     Failure/Error: it { is_expected.to match({ procedure.id => 1 }) }
     
       expected {} to match {75=>1}
       Diff:
       @@ -1,2 +1 @@
       -75 => 1,
       
     # ./spec/models/gestionnaire_spec.rb:347:in `block (4 levels) in <top (required)>'

  7) Gestionnaire#notification_for_procedure when there is a modification on avis should match [28]
     Failure/Error: it { is_expected.to match([dossier.id]) }
       expected [] to match [28]
     # ./spec/models/gestionnaire_spec.rb:319:in `block (4 levels) in <top (required)>'

  8) Gestionnaire#notification_for_procedure the messagerie when there is a new commentaire should match [30]
     Failure/Error: it { is_expected.to match([dossier.id]) }
       expected [] to match [30]
     # ./spec/models/gestionnaire_spec.rb:326:in `block (5 levels) in <top (required)>'

  9) Gestionnaire#notification_for_procedure when there is a modification on a piece justificative should match [38]
     Failure/Error: it { is_expected.to match([dossier.id]) }
       expected [] to match [38]
     # ./spec/models/gestionnaire_spec.rb:301:in `block (4 levels) in <top (required)>'

  10) Gestionnaire#notification_for_procedure when there is a modification on public champs should match [40]
      Failure/Error: it { is_expected.to match([dossier.id]) }
        expected [] to match [40]
      # ./spec/models/gestionnaire_spec.rb:278:in `block (4 levels) in <top (required)>'

  11) Gestionnaire#notification_for_procedure when there is a modification on public champs should match [42]
      Failure/Error: it { expect(gestionnaire_2.notifications_for_procedure(procedure)).to match([dossier.id]) }
        expected [] to match [42]
      # ./spec/models/gestionnaire_spec.rb:279:in `block (4 levels) in <top (required)>'

  12) Gestionnaire#notification_for_procedure when there is a modification on public champs when gestionnaire update it s public champs last seen should match [48]
      Failure/Error: it { expect(gestionnaire_2.notifications_for_procedure(procedure)).to match([dossier.id]) }
        expected [] to match [48]
      # ./spec/models/gestionnaire_spec.rb:294:in `block (5 levels) in <top (required)>'

  13) Gestionnaire#notification_for_procedure when there is a modification on public champs and there is a modification on private champs should match [50]
      Failure/Error: it { is_expected.to match([dossier.id]) }
        expected [] to match [50]
      # ./spec/models/gestionnaire_spec.rb:285:in `block (5 levels) in <top (required)>'

  14) Gestionnaire#notification_for_procedure when there is a modification on private champs should match [52]
      Failure/Error: it { is_expected.to match([dossier.id]) }
        expected [] to match [52]
      # ./spec/models/gestionnaire_spec.rb:313:in `block (4 levels) in <top (required)>'

Top 10 slowest examples (72.28 seconds, 51.8% of total time):
  users: flux de commentaires seuls les commentaires généraux sont affichés
    32.21 seconds ./spec/features/users/flux_de_commentaires_spec.rb:21
  The user fill a dossier
    19.69 seconds ./spec/features/new_user/dossier_spec.rb:14
  As a User I wanna create a dossier Right after sign_in I shall see inscription by credentials/siret, I can create a new Dossier Identification through siret
    4.72 seconds ./spec/features/users/dossier_creation_spec.rb:65
  As an administrateur I wanna create a new procedure Editing a new procedure After adding champ and file, check impossibility to publish procedure, add accompagnateur and make publication
    4.66 seconds ./spec/features/admin/procedure_creation_spec.rb:82
  As an administrateur I wanna create a new procedure Editing a new procedure Add champ, add file, visualize them in procedure preview
    3.11 seconds ./spec/features/admin/procedure_creation_spec.rb:62
  The user save an incomplete dossier as draft but cannot not submit it
    2.74 seconds ./spec/features/new_user/dossier_spec.rb:91
  As an administrateur I wanna create a new procedure Creating a new procedure Finding save button for new procedure, libelle, description and cadre_juridique required
    2.16 seconds ./spec/features/admin/procedure_creation_spec.rb:38
  user arrive on siret page when user is not logged in when he enter login information when enter a siret he is redirected to recap info entreprise page
    1.48 seconds ./spec/features/users/start_demande_spec.rb:41
  move up button type de champs when clicking on move down for type de champ 1 it switches type_de_champ 1 and 2 place 
    0.95679 seconds ./spec/features/admin/move_up_type_de_champ_private_spec.rb:24
  As an administrateur I wanna create a new procedure Creating a new procedure Finding new procedure link
    0.56367 seconds ./spec/features/admin/procedure_creation_spec.rb:32

Top 10 slowest example groups:
  users: flux de commentaires
    32.22 seconds average (32.22 seconds / 1 example) ./spec/features/users/flux_de_commentaires_spec.rb:3
  The user
    11.21 seconds average (22.42 seconds / 2 examples) ./spec/features/new_user/dossier_spec.rb:3
  As an administrateur I wanna create a new procedure
    1.69 seconds average (11.84 seconds / 7 examples) ./spec/features/admin/procedure_creation_spec.rb:4
  As a User I wanna create a dossier
    1.37 seconds average (5.47 seconds / 4 examples) ./spec/features/users/dossier_creation_spec.rb:3
  move up button type de champs
    0.95914 seconds average (0.95914 seconds / 1 example) ./spec/features/admin/move_up_type_de_champ_private_spec.rb:3
  user arrive on siret page
    0.56531 seconds average (1.7 seconds / 3 examples) ./spec/features/users/start_demande_spec.rb:3
  admin/gestionnaires/index.html.haml
    0.26391 seconds average (0.52783 seconds / 2 examples) ./spec/views/admin/gestionnaires/index.html.haml_spec.rb:3
  new_gestionnaire/dossiers/print.html.haml
    0.22838 seconds average (0.45675 seconds / 2 examples) ./spec/views/new_gestionnaire/dossiers/print.html.haml_spec.rb:1
  Gestionnaire
    0.16659 seconds average (7.33 seconds / 44 examples) ./spec/models/gestionnaire_spec.rb:3
  DossiersSerializer
    0.13142 seconds average (0.13142 seconds / 1 example) ./spec/serializers/dossiers_serializer_spec.rb:1

Finished in 2 minutes 19.6 seconds (files took 35.14 seconds to load)
945 examples, 14 failures, 1 pending

Failed examples:

rspec ./spec/models/gestionnaire_spec.rb:245 # Gestionnaire#notifications_for_dossier messagerie when there is a new commentaire should match {:demande=>false, :annotations_privees=>false, :avis=>false, :messagerie=>true}
rspec ./spec/models/gestionnaire_spec.rb:226 # Gestionnaire#notifications_for_dossier when there is a modification on a piece jusitificative should match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
rspec ./spec/models/gestionnaire_spec.rb:232 # Gestionnaire#notifications_for_dossier when there is a modification on private champs should match {:demande=>false, :annotations_privees=>true, :avis=>false, :messagerie=>false}
rspec ./spec/models/gestionnaire_spec.rb:238 # Gestionnaire#notifications_for_dossier when there is a modification on avis should match {:demande=>false, :annotations_privees=>false, :avis=>true, :messagerie=>false}
rspec ./spec/models/gestionnaire_spec.rb:220 # Gestionnaire#notifications_for_dossier when there is a modification on public champs should match {:demande=>true, :annotations_privees=>false, :avis=>false, :messagerie=>false}
rspec ./spec/models/gestionnaire_spec.rb:347 # Gestionnaire#notifications_per_procedure when there is a modification on public champs should match {75=>1}
rspec ./spec/models/gestionnaire_spec.rb:319 # Gestionnaire#notification_for_procedure when there is a modification on avis should match [28]
rspec ./spec/models/gestionnaire_spec.rb:326 # Gestionnaire#notification_for_procedure the messagerie when there is a new commentaire should match [30]
rspec ./spec/models/gestionnaire_spec.rb:301 # Gestionnaire#notification_for_procedure when there is a modification on a piece justificative should match [38]
rspec ./spec/models/gestionnaire_spec.rb:278 # Gestionnaire#notification_for_procedure when there is a modification on public champs should match [40]
rspec ./spec/models/gestionnaire_spec.rb:279 # Gestionnaire#notification_for_procedure when there is a modification on public champs should match [42]
rspec ./spec/models/gestionnaire_spec.rb:294 # Gestionnaire#notification_for_procedure when there is a modification on public champs when gestionnaire update it s public champs last seen should match [48]
rspec ./spec/models/gestionnaire_spec.rb:285 # Gestionnaire#notification_for_procedure when there is a modification on public champs and there is a modification on private champs should match [50]
rspec ./spec/models/gestionnaire_spec.rb:313 # Gestionnaire#notification_for_procedure when there is a modification on private champs should match [52]

Randomized with seed 34033

Exited with code 1
```

**Comment by kemenaran** [comment]
@fredZen je n'arrive pas à reproduire, même avec le même commit et la même seed. Tu as des pistes là dessus ? Tu as revu le souci depuis ?
